FROM mcr.microsoft.com/dotnet/sdk:10.0 AS migration

WORKDIR /src

COPY ["taskAPI/taskAPI.csproj", "taskAPI/"]
COPY ["Infrastructure/Infrastructure.csproj", "Infrastructure/"]
COPY ["Entities/Entities.csproj", "Entities/"]

RUN dotnet restore "./taskAPI/taskAPI.csproj"

COPY . .

WORKDIR "/src"

ENV ConnectionStrings__DefaultConnection="Host=postgres;Port=5432;Database=taskdb;Username=taskuser;Password=taskpass123"

RUN dotnet tool install --global dotnet-ef --version 10.0.11

RUN echo "Running migrations..." && \
    /root/.dotnet/tools/dotnet-ef database update \
    --project Infrastructure/Infrastructure.csproj \
    --startup-project taskAPI/taskAPI.csproj \
    --verbose && \
    echo "Migrations completed successfully!"
