services:
  postgres:
    image: postgres:16-alpine
    container_name: task-postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: task-migrate
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=taskdb;Username=taskuser;Password=taskpass123"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: /bin/sh
    command:
      - -c
      - |
        dotnet tool install --global dotnet-ef --version 10.0.11
        export PATH=/root/.dotnet/tools:$PATH
        dotnet-ef database update --project Infrastructure/Infrastructure.csproj --startup-project taskAPI/taskAPI.csproj
    profiles:
      - migrate

  taskapi:
    build:
      context: .
      dockerfile: ./taskAPI/Dockerfile
    container_name: task-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=taskdb;Username=taskuser;Password=taskpass123"
      Jwt__Issuer: task4-api
      Jwt__Audience: task4-client
      Jwt__Key: "UFAZMVoSYYKEy84RhuA1Scn4PpqDlSvf16PGQ96s14U="
      Jwt__ExpiresMinutes: 60
      App__PublicBaseUrl: "http://localhost:8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
